# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    env:
      CC_TEST_REPORTER_ID: 8a2453d074f6da747259e1908df35ab1d8c8fa4c3ebacacdf43c2c464bd24abb
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run NPM CI
      run: npm ci
    - name: Run NPM Build
      run: npm run build --if-present
    - name: Run Linters
      run: npm run lint
    - name: Run Unit Tests
      run: npm test
